/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package _07_GUI;

import _04_OperatingSystem.IOPetition;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.border.BevelBorder;

/**
 *
 * @author AresR
 */
public class PetitionPanel extends javax.swing.JPanel {

    private final IOPetition petition;
    
    /**
     * Creates new form NewJPanel
     */
    public PetitionPanel(IOPetition petition) {
        this.petition = petition;
        initComponents();
        // Configuración básica del panel
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        this.setPreferredSize(new Dimension(180, 70));
        this.setMaximumSize(new Dimension(250, 70));
        this.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        
        // Color de fondo distintivo para peticiones (Cian suave)
        this.setBackground(new Color(224, 255, 255)); 

        // 1. Etiqueta: Acción (Ej: READ_FILE)
        JLabel actionLabel = new JLabel(petition.getAction().toString());
        actionLabel.setFont(new Font("Segoe UI", Font.BOLD, 12));
        actionLabel.setForeground(new Color(0, 102, 102)); // Texto oscuro
        actionLabel.setAlignmentX(CENTER_ALIGNMENT);

        // 2. Etiqueta: Recurso (Ej: Tesis.docx)
        JLabel resourceLabel = new JLabel(petition.getCatalog().getName());
        resourceLabel.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        resourceLabel.setAlignmentX(CENTER_ALIGNMENT);

        // 3. Etiqueta: Proceso Solicitante (PID)
        JLabel pidLabel = new JLabel("PID: " + petition.getProcessReference().getPID());
        pidLabel.setFont(new Font("Monospaced", Font.BOLD, 10));
        pidLabel.setForeground(Color.DARK_GRAY);
        pidLabel.setAlignmentX(CENTER_ALIGNMENT);

        // Añadir componentes con espaciado
        this.add(javax.swing.Box.createVerticalStrut(5));
        this.add(actionLabel);
        this.add(javax.swing.Box.createVerticalStrut(2));
        this.add(resourceLabel);
        this.add(javax.swing.Box.createVerticalStrut(2));
        this.add(pidLabel);
        this.add(javax.swing.Box.createVerticalStrut(5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
